# Generated by Django 5.0 on 2023-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='panding', max_length=50),
        ),
    ]
